train:
    path:
        output_dir: ./model/train_dataset/
        dataset_name: ../data/train_dataset/
        delete_exist_output: True

    stage:
        do_train: True
        do_eval: True
        overwrite_cache: True

    model:
        num_train_epochs: 3
        per_device_train_batch_size: 8
        learning_rate: 5e-5
        warmup_steps: 500
        weight_decay: 0.01

test:
    path:
        output_dir: ./outputs/test_dataset/
        dataset_name: ../data/test_dataset/
        model_name_or_path: ./models/train_dataset/
        delete_exist_output: False

    stage:
        do_train: False
        do_eval: False
        do_predict: True