method: 'random'
parameters:
    learning_rate:
        distribution: 'uniform'
        min: 1e-5
        max: 1e-4
    label_smoothing_factor:
        values: [0., 0.1]
    warmup_steps:
        values: [250, 500]
    weight_decay:
        values: [0.01, 0.005]
metric:
    name: 'eval/exact_match'
    goal: 'maximize'